export const translations = 
{

  ar: {

login: "تسجيل الدخول",
fullName: "الاسم الكامل",
phonePlaceholder: "رقم الهاتف",
otpPlaceholder: "أدخل رمز التحقق (OTP)",
newPasswordPlaceholder: "كلمة المرور الجديدة",
confirmPasswordPlaceholder: "تأكيد كلمة المرور الجديدة",
savePassword: "حفظ وتغيير كلمة المرور",


    loginTitle: "تسجيل الدخول",
    loginSubtitle: "سجل دخولك لإدارة فعالياتك",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    btnCustomer: "الدخول كـ زبون",
    btnAgent: "الدخول كـ وكيل فعاليات",
    alertTitle: "تنبيه",
    alertMessage: "الرجاء إدخال البريد الإلكتروني وكلمة المرور",
    customerTitle: "أهلاً بك في قسم إدارة فعالياتك",
    agentTitle: "أهلاً بك في لوحة الإشراف الميداني",
    logout: "تسجيل الخروج",
    changeLang: "تغيير اللغة",
    changeTheme: "تغيير المظهر",
    home: "الرئيسية",
    notifications: "الإشعارات",
    myEvents: "فعالياتي",
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف الشخصي",
    saveChanges: "حفظ التعديلات",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    gender: "الجنس",
    birthday: "تاريخ الميلاد",
    confirmPassword: "تأكيد كلمة المرور",
    agreeTerms: "أنا أوافق على الشروط وسياسة الخصوصية",
    signup: "إنشاء حساب جديد",
    orSignInWith: "أو سجل دخولك عبر",
    dontHaveAccount: "ليس لديك حساب؟ ",
    createAccount: "أنشئ حساباً",
    alreadyHaveAccount: "لديك حساب بالفعل؟ ",
    loginHere: "سجل دخولك",
    selectGender: "اختر الجنس",
    male: "ذكر",
    female: "أنثى",
    noNotifications: "لا توجد إشعارات جديدة حالياً",
    noEvents: "لم تقم بإنشاء أي فعالية بعد",
    photoAlertTitle: "صورة الحساب",
    photoAlertMessage: "اختر طريقة رفع الصورة ",
    camera: "التقاط صورة بالكاميرا",
    gallery: "اختيار من معرض الصور",
    cancel: "إلغاء",
    "forgotPassword": "نسيت كلمة المرور",
  "forgotPasswordSubtitle": "أدخل بريدك الإلكتروني وسنرسل لك رمز التحقق",
  "sendResetCode": "إرسال رمز التحقق",
  "backToLogin": "العودة إلى تسجيل الدخول",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "resetPasswordSubtitle": "أدخل رمز التحقق وكلمة المرور الجديدة",
  "otpCode": "رمز التحقق (OTP)",
  "newPassword": "كلمة المرور الجديدة",
  "confirmNewPassword": "تأكيد كلمة المرور الجديدة",
  "resetPasswordBtn": "تغيير كلمة المرور",
  "enterEmailFirst": "الرجاء إدخال البريد الإلكتروني أولاً",
  "otpSentMessage": "تم إرسال رمز استعادة كلمة المرور إلى بريدك الإلكتروني",
  "fillAllFields": "الرجاء ملء جميع الحقول",
  "passwordChangedSuccess": "تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة",
  "passwordMinLength": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
  planNewEvent: "تخطيط مناسبة جديدة",
  approvedVenues: "قائمة الصالات المعتمدة",
  myEventsList: "قائمة مناسباتي",
  venueStatus: "حالة الصالة",
  vendorStatus: "حالة الموردين",
  paymentInvoiceStatus: "حالة الفاتورة النهائية والدفع",
  notificationsCenter: "مركز الإشعارات",
  clearTokenLogout: "تسجيل خروج ومسح الـ Token",
  uploadAvatar: "رفع وتغيير الصورة الشخصية",

    createEventTitle: "تصميم فعاليتك ",
    nextStep: "التالي ➡️",
    prevStep: "⬅️ السابق",
    submitEvent: "إرسال وتأكيد الفعالية ⚜️",
    eventType: "نوع المناسبة",
    eventDateTime: "التاريخ والتوقيت",
    selectVenue: "اختيار الصالة",
    selectServices: "قائمة الخدمات الملوكية المفصلة",
    selectQuantities: "تحديد الكميات والمقاعد",
    reviewSummary: "مراجعة كشف الحساب والملخص",
    
    venue1: "قاعة الماسة الكبرى (شاملة الوجبات)",
    venue2: "منتجع الورد المخملي (مفتوح)",
    serviceFood: "بوفيه عشاء ملكي",
    serviceFlowers: "تنسيق زهور طبيعية VIP",
    serviceCars: "موكب سيارات ليموزين",
    
    totalPrice: "إجمالي التكلفة التقديرية",
    eventStatus: "حالة الطلب",
    statusPending: "بانتظار موافقة الموردين ⏳",
    statusConfirmed: "مؤكد - جاهز للدفع الجزئي 💳",
    payDeposit: "دفع العربون الآن",
    paymentSuccess: "تم الدفع بنجاح! فعاليتك مغطاة بالكامل ⚜️",

    celebratingTitle: "ماذا سنحتفل اليوم؟",
    createEventBtn: "✨ أنشئ فعاليتك الآن",
    selectEventType: "اختر نوع المناسبة",
    selectDate: "اختر التاريخ والوقت",
    setBudget: "تحديد الميزانية الإجمالية ($)",
    reviewSubmit: "مراجعة وإرسال الطلب",
    submitOrder: "👑 إرسال الطلب للموردين",
    budgetPlaceholder: "أدخل الميزانية المقدرة مثلاً: 5000",
    
    wedding: "زواج",
    birthday: "عيد ميلاد",
    graduation: "حفل تخرج",
    corporate: "اجتماعات شركات",
    funeral: "مجالس عزاء تذكارية",
    engagement: "حفل خطوبة",
    babyShower: "استقبال مواليد وأسبوع فخم 🍼",
    awards: "مهرجانات تكريم وتوزيع جوائز 🏆",
    
    food: "بوفيه الأطعمة",
    drinks: "المشروبات والبار",
    flowers: "الورود والكوشة",
    cars: "السيارات الفارهة",
    sweets: "كيك وحلويات",
    fruits: "بوفيه الفواكه",

    appName: "⚜️ إيفينتك",
    cartTitle: "حقيبة الخدمات المختارة",
    remainingBudget: "المتبقي من الميزانية:",
    itemsCount: "خدمات مفعلة",
    unit: "وحدة",
    exceededBudget: "⚠️ تنبيه: تجاوزت الميزانية المطلوبة!",

    fruitSculptures: "منحوتات فواكه استوائية",
    fruitPlatterClassic: "طبق فواكه مشكلة كلاسيك",
    fruitBasketRoyal: "سلة فواكه الأناناس الملكية",
    fruitMelonBoat: "قارب البطيخ بالـ VIP فواكه",
    fruitTowerPremium: "ستاند طبقات الفواكه الفاخر",
    fruitBowlMix: "صحون سلطة فواكه ملوكية",
    pomegranatePlate: "طبق رمان ياقوتي طازج",
    strawberryPlate: "طبق فراولة مخملية طازجة",
    kiwiPlate: "طبق شرائح الكيوي المنعشة",
    exoticFruitPlatter: "صينية الفواكه الاستوائية النادرة",

    blackStar: "كوشة ورد طبيعي هولندي",
    boatOrchid: "ممرات ورود بيضاء فخمة",
    camellia: "تنسيق كاميليا ملكي",
    boldDaisy: "باقة ديزي الخريفية",
    damaskRose: "فازة الورد الجوري الفاخر",
    hydrangea: "تنسيق هيدرانجيا ملكي",
    jasmine: "باقة الياسمين الدمشقي",
    narcissus: "فازة النرجس البري",
    orichid: "ستاند أوركيد الأناقة",
    tulips: "فازة التوليب الوردي",

    carRollsClassic: "رولس رويس كلاسيك ملوكي",
    carAudiA8L: "أودي A8L فخامة رئاسية",
    carBentleySUV: "بينتلي بنتايجا VIP",
    carDefenderLuxury: "لاند روفر ديفندر ملكي ممتد",
    carLimousineVIP: "ليموزين لينكولن أسطوري طويل",
    carMaybachSClass: "مرسيدس مايباخ روز غولد سبيشال",
    carMercedesCabrio: "مرسيدس كابريو مكشوفة كلاسيك",
    carMercedesGClass: "موكب مرسيدس G-Class دمشقي فخم",
    carPorschePanamera: "بورش باناميرا رياضية فخمة",
    carRollsPhantom: "رولس رويس فانتوم أزرق ملوكي",

dessertClassic: "هرم ماكارون الألوان الفاخر",
dessertLuxury: "شريحة كيك الفراولة المخملية الأبيض",
dessertRoyal: "كيك غلاساج التوت الأحمر الملكي",
dessertSpecial: "تارت الليمون بالميرنغ السويسري",
dessertPremium: "كيك سان هونوريه بالفانيليا والكراميل",
dessertMix: "كريم بروليه فرنسي كلاسيكي",
dessertChocoPlate: "شريط الماكارون الفرنسي الفاخر",
dessertBerryPlate: "قبة التوت والورد المخملية اللامعة",
dessertCreamyCup: "تارت الشوكولاتة الداكنة بزهور الذهب",
dessertExoticPlatter: "كأس بانابوتا التوت المشكل الفاخر",
dessertFruitCake: "كيكة بالفواكه الطازجة",
dessertWalnutNest: "عش البلبل بالجوز",
dessertPistachioRoll: "مبرومة بالفستق الحلبي",
dessertAshtaNest: "عش البلبل بالقشطة والفستق",
dessertBasbousaPistachio: "بسبوسة بالفستق الحلبي",
dessertBasbousaAlmond: "بسبوسة باللوز",
dessertWeddingCake: "قالب كيك الأعراس الملكي",
dessertAssortedBaklava: "مشكل حلويات شرقية فاخرة",
dessertKunafa: "كنافة نابلسية بالقشطة والجبن",


drinkBitterCoffee: "قهوة مرّة أصيلة",
drinkChampagne: "مشروب الشامبانيا الفاخر",
drinkCocktail: "كوكتيل الفواكه الإستوائية",
drinkEnergyDrinks: "مشروبات الطاقة المنعشة",
drinkFizzyDrinks: "مشروبات غازية فوارة",
drinkFreshJuice: "عصائر طبيعية طازجة",
drinkHerbalTea: "شاي الأعشاب العطرية المهدئ",
drinkHotDrinks: "مشروبات ساخنة دافئة",
drinkMilkShake: "ميلك شيك مخملي بارد",
drinkWhiskey: "مشروب الويكسي العريق",


appetizerBabaGhanoush: "متبل باذنجان (بابا غنوج) فاخر بزهور الذهب",
appetizerBeefCarpaccio: "كارباتشيو لحم البقر الفاخر",
appetizerCheeseSambousek: "سمبوسك بالجبن مقرمشة مع رقائق الذهب",
appetizerGoatCheeseHoney: "تارتليت جبن الماعز الفاخر بالعسل والكافيار اللامع",
appetizerGourmetSambousek: "تشكيلة سمبوسك وغوزميه شرقية فاخرة بالفستق",
appetizerHummusFatteh: "كؤوس فتة الحمص المقرمشة مع الصنوبر والذهب",
appetizerHummusCaviar: "حمص ملكي مزين بالكافيار الأسود والذهبي والأعشاب الطازجة",
appetizerKibbehNayyeh: "كبة نيئة فاخرة منسقة بلمسة ذهبية وأعشاب",
appetizerMiniQuiche: "ميني كيش فرنسي مخبوز بالخضار ورقائق الذهب",
appetizerDolma: "ورق عنب (دولما) فاخر بدبس الرمان والكافيار الأسود",
appetizers: "المقبلات",


food: "الأطباق الرئيسية",
  foodFiletMignon: "فيليه مينيون فاخر",
  foodFoieGras: "كبد الأوز (فوا جرا) ملكي",
  foodJagerschnitzel: "شنيتزل بالفطر على الطريقة الألمانية",
  foodLobsterThermidor: "استاكوزا (لوبستر) ثيرميدور اللذيذة",
  foodPekingDuck: "بط بكين المقرمش التقليدي",
  foodRisottoAiFunghi: "ريزوتو الفطر الإيطالي البري",
  foodSaffronRisotto: "ريزوتو الزعفران الفاخر بورق الذهب",
  foodSquidInkCalamari: "كلماري محشي بحبر الحبار",
  foodTagliatelleTartufo: "باستا تاليscaleاتيلي بالكمأة السوداء",
  foodTurbotChampagne: "سمك الترس بصلصة الشامبانيا الفاخرة",

  appetizerCrunchyRoastedChickpeas: "حمص محمص مقرمش",
appetizerMarinatedOlives: "زيتون متبل",
appetizerAleppoPistachios: "فستق حلبي",
appetizerRoastedCashews: "كاجو محمص",
appetizerRoastedMixedNuts: "مكسرات مشكلة محمصة",
appetizerRoastedPumpkinSeeds: "بذور اليقطين المحمصة (بزر أبيض)",
appetizerSaltedPeanuts: "فستق عبيد مملح (فول سوداني)",
appetizerSaltedRoastedAlmonds: "لوز محمص ومملح",
appetizerShanklishCheese: "جبنة شنكليش بالخضار",



hallRoyalGrand: "القاعة الملكية الكبرى",
    hallCrystalBallroom: "قاعة الكريستال الفاخرة",
    hallGoldenOasis: "قاعة الواحة الذهبية",
    hallMajesticPalace: "قاعة القصر المهيب",
    hallSapphireLounge: "صالة الياقوت",
    hallEmeraldGarden: "قاعة حديقة الزمرد",
    hallDiamondPavilion: "الجناح الماسي الفاخر",
    hallSunsetTerrace: "قاعة تراس الغروب",
    hallVintageClassic: "القاعة الكلاسيكية القديمة",


"profile": "الملف الشخصي",
  "availableBalance": "الرصيد المتاح",
  "topUp": "شحن الرصيد",
  "fullName": "الاسم الكامل",
  "phoneNumber": "رقم الهاتف",
  "saveChanges": "حفظ التعديلات",
  "editProfile": "تعديل الحساب",
  "topUpCard": "شحن بطاقة الدفع",
  "enterAmount": "أدخل المبلغ",
  "cancel": "إلغاء",
  "sendRequest": "إرسال الطلب",
  "appOptions": "خيارات التطبيق",
  "support": "الدعم الفني",
  "aboutApp": "حول التطبيق",
  "termsServices": "الشروط والأحكام",
  "settings": "الإعدادات",
  "success": "نجاح",
  "error": "خطأ",
  "profileUpdated": "تم تحديث الملف الشخصي بنجاح",
  "invalidAmount": "يرجى إدخال مبلغ شحن صحيح أكبر من الصفر",
  "requestSent": "تم إرسال الطلب",
  "topUpPendingAdmin": "تم إرسال طلب شحن البطاقة للأدمن، بانتظار الموافقة.",
helpCenter: "مركز الدعم والمساعدة",
    paymentHistory: "سجل العمليات المالية",
    settings: "إعدادات الحساب",
    termsConditions: "الشروط والسياسات",
    logout: "تسجيل الخروج",
    availableBalance: "الرصيد المتاح",
    topUp: "شحن رصيد",
    editProfile: "تعديل الحساب",
    moreOptions: "خيارات التطبيق والدعم",
    topUpTitle: "طلب شحن رصيد",
    enterAmount: "أدخل المبلغ المراد إرساله للأدمن",
    profileUpdated: "تم تحديث بيانات الملف الشخصي والصورة فورياً",
    topUpRequestSent: "تم إرسال طلب شحن البطاقة للادمن بانتظار الموافقة",
    invalidAmount: "الرجاء إدخال قيمة صحيحة",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    send: "إرسال",
    alertTitle: "تنبيه",
    comingSoon: "قريباً في التحديث القادم",



  'onboardingTitle1': 'تنظيم فعاليات ومناسبات',
    'onboardingDesc1': 'خطط ونظم فعالياتك بكل سهولة واحترافية مع Eventak',
    'onboardingTitle2': 'اختر صالة المناسبات المثالية',
    'onboardingDesc2': 'تصفح أفضل صالات المناسبات واختر ما يناسب ذوقك ومناسبتك',
    'onboardingTitle3': 'قائمة طعام متكاملة',
    'onboardingDesc3': 'اختر من تشكيلة واسعة من المأكولات والمشروبات والحلويات',
    'onboardingTitle4': 'سيارات فاخرة لمناسباتك',
    'onboardingDesc4': 'أضف لمسة من الفخامة مع تشكيلة من السيارات الراقية',
    'skip': 'تخطي',
    'next': 'التالي',
    'getStarted': 'ابدأ الآن',
    
  },

  en: {


login: "Login",
fullName: "Full Name",
phonePlaceholder: "Phone Number",
otpPlaceholder: "Enter verification code (OTP)",
newPasswordPlaceholder: "New Password",
confirmPasswordPlaceholder: "Confirm New Password",
savePassword: "Save & Change Password",


    loginTitle: "Log In",
    loginSubtitle: "Sign in to manage your events",
    emailPlaceholder: "Email Address",
    passwordPlaceholder: "Password",
    btnCustomer: "Login as Customer",
    btnAgent: "Login as Agent",
    alertTitle: "Alert",
    alertMessage: "Please enter email and password",
    customerTitle: "Welcome to your Event Management",
    agentTitle: "Welcome to Field Supervision Board",
    logout: "Logout",
    changeLang: "Language",
    changeTheme: "Theme",
    home: "Home",
    notifications: "Notifications",
    myEvents: "My Events",
    profile: "Profile",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    firstName: "First Name",
    lastName: "Last Name",
    gender: "Gender",
    birthday: "Birthday",
    confirmPassword: "Confirm Password",
    agreeTerms: "I agree to the Terms & Privacy Policy",
    signup: "SIGN UP",
    orSignInWith: "Or sign in with",
    dontHaveAccount: "Don't have an account? ",
    createAccount: "Sign Up",
    alreadyHaveAccount: "Already have an account? ",
    loginHere: "Login",
    selectGender: "Select Gender",
    male: "Male",
    female: "Female",
    noNotifications: "No new notifications at the moment",
    noEvents: "You have not created any events yet",
    photoAlertTitle: "Profile Photo",
    photoAlertMessage: "Select how you want to upload your photo",
    camera: "Take Photo via Camera",
    gallery: "Choose from Gallery",
    cancel: "Cancel",
"forgotPassword": "Forgot Password",
  "forgotPasswordSubtitle": "Enter your email and we'll send you a verification code",
  "sendResetCode": "Send Reset Code",
  "backToLogin": "Back to Login",
  "resetPassword": "Reset Password",
  "resetPasswordSubtitle": "Enter the verification code and your new password",
  "otpCode": "Verification Code (OTP)",
  "newPassword": "New Password",
  "confirmNewPassword": "Confirm New Password",
  "resetPasswordBtn": "Change Password",
  "enterEmailFirst": "Please enter your email address first",
  "otpSentMessage": "Password reset code has been sent to your email",
  "fillAllFields": "Please fill in all fields",
  "passwordChangedSuccess": "Password changed successfully. You can now login with your new password",
  "passwordMinLength": "Password must be at least 6 characters",



 planNewEvent: "Plan a New Event",
  approvedVenues: "Approved Venues List",
  myEventsList: "My Events List",
  venueStatus: "Venue Status",
  vendorStatus: "Vendor Status",
  paymentInvoiceStatus: "Final Invoice & Payment Status",
  notificationsCenter: "Notifications Center",
  clearTokenLogout: "Logout & Clear Token",
  uploadAvatar: "Upload Personal Avatar",
    
    venue1: "The Grand Diamond Hall (All-Inclusive)",
    venue2: "Velvet Rose Resort (Open Air)",
    serviceFood: "Royal Dinner Buffet",
    serviceFlowers: "VIP Natural Flowers Design",
    serviceCars: "Limousine Convoy Service",
    
    totalPrice: "Total Estimated Price",
    eventStatus: "Event Status",
    statusPending: "Pending Vendors Confirmation ⏳",
    statusConfirmed: "Confirmed - Ready for Deposit 💳",
    payDeposit: "Pay Deposit Now",
    paymentSuccess: "Payment Successful! Event Fully Secured ⚜️",

    celebratingTitle: "What are we celebrating today?",
    createEventBtn: "✨ Create Event Now",
    selectEventType: "Select Event Type",
    selectDate: "Select Date & Time",
    setBudget: "Set Total Budget ($)",
    reviewSubmit: "Review & Submit",
    submitOrder: "👑 Submit Royal Request",
    budgetPlaceholder: "Enter budget e.g. 5000",

    wedding: "Weddings",
    birthday: "Birthdays",
    graduation: "Graduations",
    corporate: "Corporate Meetings",
    funeral: "Funerals & Memorials",
    engagement: "Engagements",
    babyShower: "Luxury Baby Showers 🍼",
    awards: "Gala & Awards Ceremonies 🏆",

    food: "Catering & Food",
    drinks: "Drinks Bar",
    flowers: "Flowers & Stage",
    cars: "VIP Cars Fleet",
    sweets: "Wedding Cakes & Desserts",
    fruits: "Fruits Buffet",

    appName: "⚜️ Even(T)ak",
    cartTitle: "Selected Services Bag",
    remainingBudget: "Remaining Budget:",
    itemsCount: "Active Services",
    unit: "Unit",
    exceededBudget: "⚠️ Warning: Budget Exceeded!",

    // Fruit Buffet Items
    fruitSculptures: "Exotic Fruit Sculptures",
    fruitPlatterClassic: "Classic Mixed Fruit Platter",
    fruitBasketRoyal: "Royal Pineapple Fruit Basket",
    fruitMelonBoat: "VIP Melon Fruit Boat",
    fruitTowerPremium: "Premium Tiered Fruit Stand",
    fruitBowlMix: "Royal Fruit Salad Bowls",
    pomegranatePlate: "Fresh Ruby Pomegranate Plate",
    strawberryPlate: "Fresh Velvet Strawberry Plate",
    kiwiPlate: "Refreshing Kiwi Slices Plate",
    exoticFruitPlatter: "Rare Exotic Fruit Platter",

    // Flowers & Stage Items
    blackStar: "Royal Black Star & Dark Calla Bouquet",
    boatOrchid: "Luxury Velvet Boat Orchid Arrangement",
    camellia: "Classic Imperial Camellia Vase",
    boldDaisy: "Warm Autumn Daisy & Dahlia Bouquet",
    damaskRose: "Noble Heritage Damask Rose Vase",
    hydrangea: "Royal Hydrangea & Premium Dahlia Arrangement",
    jasmine: "Fresh Syrian Jasmine & Yellow Rose Design",
    narcissus: "Imperial Spring White & Yellow Narcissus Setup",
    orichid: "Elegant White & Yellow Orchid Arrangement",
    tulips: "Velvet Pink Harmony Tulips Vase",

    // VIP Cars Items
    carRollsClassic: "Royal Classic Rolls-Royce",
    carAudiA8L: "Presidential Luxury Audi A8L",
    carBentleySUV: "VIP Bentley Bentayga",
    carDefenderLuxury: "Royal Extended Land Rover Defender",
    carLimousineVIP: "Legendary Stretch Lincoln Limousine",
    carMaybachSClass: "Special Rose Gold Mercedes-Maybach",
    carMercedesCabrio: "Classic Open-Top Mercedes Cabrio",
    carMercedesGClass: "Luxury Damascus Mercedes G-Class Convoy",
    carPorschePanamera: "Premium Sporty Porsche Panamera",
    carRollsPhantom: "Royal Blue Rolls-Royce Phantom",

dessertClassic: "Luxury Colorful Macaron Pyramid",
dessertLuxury: "White Strawberry Velvet Cake Slice",
dessertRoyal: "Royal Raspberry Glaze Cake",
dessertSpecial: "Swiss Meringue Lemon Tart",
dessertPremium: "Saint Honoré Caramel & Vanilla Pastry",
dessertMix: "Classic French Crème Brûlée",
dessertChocoPlate: "Premium French Macaron Line Selection",
dessertBerryPlate: "Glossy Rose Raspberry Velvet Dome",
dessertCreamyCup: "Dark Chocolate Tart with Golden Flower",
dessertExoticPlatter: "Premium Mixed Berry Panna Cotta Glass",
dessertFruitCake: "Fresh Fruit Cake",
dessertWalnutNest: "Walnut Bird's Nest",
dessertPistachioRoll: "Pistachio Baklava Roll",
dessertAshtaNest: "Pistachio & Cream Nest",
dessertBasbousaPistachio: "Pistachio Basbousa",
dessertBasbousaAlmond: "Almond Basbousa",
dessertWeddingCake: "Royal Wedding Cake",
dessertAssortedBaklava: "Premium Assorted Oriental Sweets",
dessertKunafa: "Traditional Kunafa with Cream",

    drinkBitterCoffee: "Authentic Bitter Coffee",
drinkChampagne: "Premium Luxury Champagne",
drinkCocktail: "Exotic Fruit Cocktail",
drinkEnergyDrinks: "Refreshing Energy Drinks",
drinkFizzyDrinks: "Sparkling Fizzy Drinks",
drinkFreshJuice: "Freshly Squeezed Juices",
drinkHerbalTea: "Soothing Aromatic Herbal Tea",
drinkHotDrinks: "Warm Artisan Hot Drinks",
drinkMilkShake: "Velvet Creamy Milkshake",
drinkWhiskey: "Classic Reserve Whiskey",

appetizerBabaGhanoush: "Luxury Baba Ghanoush Tart with Gold Leaf",
appetizerBeefCarpaccio: "Premium Beef Carpaccio Platter",
appetizerCheeseSambousek: "Crispy Cheese Sambousek with Edible Gold",
appetizerGoatCheeseHoney: "Goat Cheese & Honey Tartlets with Glossy Caviar",
appetizerGourmetSambousek: "Premium Assorted Gourmet Sambousek Selection",
appetizerHummusFatteh: "Crispy Hummus Fatteh Cups with Pine Nuts & Gold",
appetizerHummusCaviar: "Royal Hummus Platter with Black & Gold Caviar",
appetizerKibbehNayyeh: "Luxury Kibbeh Nayyeh Cups with Gold & Fresh Herbs",
appetizerMiniQuiche: "Gourmet Mini Baked Quiche with Gold Flakes",
appetizerDolma: "Premium Stuffed Grape Leaves (Dolma) with Black Caviar",
appetizers: "Appetizers",



food: "Main Dishes",
  foodFiletMignon: "Premium Filet Mignon",
  foodFoieGras: "Royal Foie Gras",
  foodJagerschnitzel: "Traditional Jägerschnitzel",
  foodLobsterThermidor: "Gourmet Lobster Thermidor",
  foodPekingDuck: "Classic Peking Duck",
  foodRisottoAiFunghi: "Wild Risotto ai Funghi",
  foodSaffronRisotto: "Saffron Risotto with Gold Leaf",
  foodSquidInkCalamari: "Squid Ink Stuffed Calamari",
  foodTagliatelleTartufo: "Tagliatelle al Tartufo Nero",
  foodTurbotChampagne: "Turbot with Champagne Sauce",


appetizerCrunchyRoastedChickpeas: "Crunchy Roasted Chickpeas",
appetizerMarinatedOlives: "Marinated Olives",
appetizerAleppoPistachios: "Aleppo Pistachios",
appetizerRoastedCashews: "Roasted Cashews",
appetizerRoastedMixedNuts: "Roasted Mixed Nuts",
appetizerRoastedPumpkinSeeds: "Roasted Pumpkin Seeds",
appetizerSaltedPeanuts: "Salted Peanuts",
appetizerSaltedRoastedAlmonds: "Salted Roasted Almonds",
appetizerShanklishCheese: "Shanklish Cheese with Vegetables",




hallRoyalGrand: "Royal Grand Hall",
    hallCrystalBallroom: "Crystal Ballroom",
    hallGoldenOasis: "Golden Oasis Hall",
    hallMajesticPalace: "Majestic Palace Hall",
    hallSapphireLounge: "Sapphire Lounge",
    hallEmeraldGarden: "Emerald Garden Hall",
    hallDiamondPavilion: "Diamond Pavilion",
    hallSunsetTerrace: "Sunset Terrace Hall",
    hallVintageClassic: "Vintage Classic Hall",



"profile": "Profile",
  "availableBalance": "Available Balance",
  "topUp": "Top Up",
  "fullName": "Full Name",
  "phoneNumber": "Phone Number",
  "saveChanges": "Save Changes",
  "editProfile": "Edit Profile",
  "topUpCard": "Top Up Payment Card",
  "enterAmount": "Enter amount",
  "cancel": "Cancel",
  "sendRequest": "Send Request",
  "appOptions": "App Options",
  "support": "Technical Support",
  "aboutApp": "About App",
  "termsServices": "Terms of Service",
  "settings": "Settings",
  "success": "Success",
  "error": "Error",
  "profileUpdated": "Profile updated successfully",
  "invalidAmount": "Please enter a valid amount greater than zero",
  "requestSent": "Request Sent",
  "topUpPendingAdmin": "Your top-up request has been sent to the admin for approval.",

helpCenter: "Help & Support",
    paymentHistory: "Payment History",
    settings: "Settings",
    termsConditions: "Terms & Conditions",
    logout: "Log Out",
    availableBalance: "Available Balance",
    topUp: "Top Up",
    editProfile: "Edit Profile",
    moreOptions: "Application Options",
    topUpTitle: "Top Up Account Balance",
    enterAmount: "Enter the amount to send to admin",
    profileUpdated: "Profile and photo updated instantly",
    topUpRequestSent: "Top-up request sent to admin, pending approval",
    invalidAmount: "Please enter a valid amount",
    name: "Name",
    email: "Email",
    password: "Password",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    send: "Send",
    alertTitle: "Notification",
    comingSoon: "Coming soon in the next update",



        'onboardingTitle1': 'Event & Occasion Planning',
    'onboardingDesc1': 'Plan and organize your events easily and professionally with Eventak',
    'onboardingTitle2': 'Choose the Perfect Venue',
    'onboardingDesc2': 'Browse the best event halls and choose what suits your taste and occasion',
    'onboardingTitle3': 'Complete Food Menu',
    'onboardingDesc3': 'Choose from a wide selection of foods, drinks, and desserts',
    'onboardingTitle4': 'Luxury Cars for Your Events',
    'onboardingDesc4': 'Add a touch of elegance with a collection of premium cars',
    'skip': 'Skip',
    'next': 'Next',
    'getStarted': 'Get Started',

  },

  fr: {

// أضف هذه الكلمات في قسم 'fr'
login: "Connexion",
fullName: "Nom Complet",
phonePlaceholder: "Numéro de téléphone",
otpPlaceholder: "Entrez le code de vérification (OTP)",
newPasswordPlaceholder: "Nouveau mot de passe",
confirmPasswordPlaceholder: "Confirmer le nouveau mot de passe",
savePassword: "Enregistrer et changer le mot de passe",


    loginTitle: "Connexion",
    loginSubtitle: "Sign in to manage your events",
    emailPlaceholder: "Adresse e-mail",
    passwordPlaceholder: "Mot de passe",
    btnCustomer: "Connexion Client",
    btnAgent: "Connexion Agent",
    alertTitle: "Alerte",
    alertMessage: "Veuillez entrer l'e-mail et le mot de passe",
    customerTitle: "Bienvenue dans la gestion de vos événements",
    agentTitle: "Bienvenue au Conseil de Supervision",
    logout: "Se déconnecter",
    changeLang: "Langue",
    changeTheme: "Thème",
    home: "Accueil",
    notifications: "Notifications",
    myEvents: "Mes Événements",
    profile: "Profil",
    editProfile: "Modifier le Profil",
    saveChanges: "Enregistrer",
    firstName: "Prénom",
    lastName: "Nom",
    gender: "Genre",
    birthday: "Date de naissance",
    confirmPassword: "Confirmer",
    agreeTerms: "J'accepte les conditions",
    signup: "S'INSCRIRE",
    orSignInWith: "Ou connectez-vous avec",
    dontHaveAccount: "Pas de compte? ",
    createAccount: "S'inscrire",
    alreadyHaveAccount: "Déjà un compte? ",
    loginHere: "Connexion",
    selectGender: "Sélectionner le genre",
    male: "Homme",
    female: "Femme",
    noNotifications: "Aucune notification pour le moment",
    noEvents: "Aucun événement créé",
    photoAlertTitle: "Photo de profil",
    photoAlertMessage: "Sélectionnez une méthode",
    camera: "Prendre une photo",
    gallery: "Choisir de la galerie",
    cancel: "Annuler",
"forgotPassword": "Mot de passe oublié",
  "forgotPasswordSubtitle": "Entrez votre email et nous vous enverrons un code de vérification",
  "sendResetCode": "Envoyer le code",
  "backToLogin": "Retour à la connexion",
  "resetPassword": "Réinitialiser le mot de passe",
  "resetPasswordSubtitle": "Entrez le code de vérification et votre nouveau mot de passe",
  "otpCode": "Code de vérification (OTP)",
  "newPassword": "Nouveau mot de passe",
  "confirmNewPassword": "Confirmer le nouveau mot de passe",
  "resetPasswordBtn": "Changer le mot de passe",
  "enterEmailFirst": "Veuillez d'abord entrer votre adresse email",
  "otpSentMessage": "Code de réinitialisation envoyé à votre email",
  "fillAllFields": "Veuillez remplir tous les champs",
  "passwordChangedSuccess": "Mot de passe changé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe",
  "passwordMinLength": "Le mot de passe doit contenir au moins 6 caractères",


    
    createEventTitle: "Concevez votre événement royal",
    nextStep: "Suivant ➡️",
    prevStep: "⬅️ Précédent",
    submitEvent: "Soumettre l'événement ⚜️",
    eventType: "Type d'événement",
    eventDateTime: "Date & Heure",
    selectVenue: "Sélectionnez la salle",
    selectServices: "Services royaux détaillés",
    selectQuantities: "Quantités & Places",
    reviewSummary: "Résumé & Facture",
    
    venue1: "Le Grand Salon Diamant",
    venue2: "Complexe Rose de Velours",
    serviceFood: "Buffet Dîner Royal",
    serviceFlowers: "Fleurs Naturelles VIP",
    serviceCars: "Convoi de Limousines",
    
    totalPrice: "Prix total estimé",
    eventStatus: "Statut",
    statusPending: "En attente de confirmation ⏳",
    statusConfirmed: "Confirmé - Prêt pour l'acompte 💳",
    payDeposit: "Payer l'acompte maintenant",
    paymentSuccess: "Paiement réussi! Événement sécurisé ⚜️",

planNewEvent: "Planifier un nouvel événement",
  approvedVenues: "Liste des salles approuvées",
  myEventsList: "Mon calendrier d'événements",
  venueStatus: "Statut de la salle",
  vendorStatus: "Statut du fournisseur",
  paymentInvoiceStatus: "Facture finale et statut du paiement",
  notificationsCenter: "Centre de notifications",
  clearTokenLogout: "Se déconnecter et effacer le token",
  uploadAvatar: "Télécharger l'avatar personnel",
    
    wedding: "Mariages",
    birthday: "Anniversaires",
    graduation: "Remise des diplômes",
    corporate: "Entreprises",
    funeral: "Funérailles",
    engagement: "Fiançailles",
    babyShower: "Fêtes de Naissance 🍼",
    awards: "Remises de Prix & Galas 🏆",
    
    food: "Restauration",
    drinks: "Bar à boissons",
    flowers: "Fleurs et scène",
    cars: "Voitures VIP",
    sweets: "Gâteaux et Pâtisseries",
    fruits: "Buffet de fruits",

    appName: "⚜️ Even(T)ak",
    cartTitle: "Sac de Services Sélectionnés",
    remainingBudget: "Budget Restant:",
    itemsCount: "Services Actifs",
    unit: "Unité",
    exceededBudget: "⚠️ Attention: Budget Dépassé!",

    // Fruits FR
    fruitSculptures: "Sculptures de Fruits Exotiques",
    fruitPlatterClassic: "Plateau de Fruits Mixte Classique",
    fruitBasketRoyal: "Panier d'Ananas Royal",
    fruitMelonBoat: "Bateau de Melon VIP",
    fruitTowerPremium: "Présentoir de Fruits Premium",
    fruitBowlMix: "Bols de Salade de Fruits",
    pomegranatePlate: "Assiette de Grenade Fraîche",
    strawberryPlate: "Assiette de Fraises Velours",
    kiwiPlate: "Assiette de Tranches de Kiwi",
    exoticFruitPlatter: "Plateau de Fruits Exotiques Rares",

    // Flowers FR
    blackStar: "Bouquet Royal de l'Étoile Noire & Calla Sombre",
    boatOrchid: "Arrangement de Luxe d'Orchidées",
    camellia: "Vase de Camélia Impérial Classique",
    boldDaisy: "Bouquet d'Automne de Marguerites & Dahlias",
    damaskRose: "Vase de Rose de Damas de Noble Héritage",
    hydrangea: "Arrangement Royal d'Hortensias & Dahlias",
    jasmine: "Design Frais de Jasmin Syrien & Roses Jaunes",
    narcissus: "Installation Impériale de Narcisses Blancs",
    orichid: "Élégant Arrangement d'Orchidées Blanches",
    tulips: "Vase de Tulipes de l'Harmonie Rose Velours",

    // Cars FR
    carRollsClassic: "Rolls-Royce Classique Royale",
    carAudiA8L: "Audi A8L Luxe Présidentiel",
    carBentleySUV: "Bentley Bentayga VIP",
    carDefenderLuxury: "Land Rover Defender Royal Rallongé",
    carLimousineVIP: "Limousine Lincoln Stretch Légendaire",
    carMaybachSClass: "Mercedes-Maybach Or Rose Spéciale",
    carMercedesCabrio: "Mercedes Cabrio Décapotable Classique",
    carMercedesGClass: "Convoi de Mercedes Classe G de Luxe",
    carPorschePanamera: "Porsche Panamera Sportive Premium",
    carRollsPhantom: "Rolls-Royce Phantom Bleu Royal",

    
dessertClassic: "Pyramide de Macarons Colorés de Luxe",
dessertLuxury: "Tranche de Gâteau Velours Fraise Blanc",
dessertRoyal: "Gâteau Royal au Glaçage Framboise",
dessertSpecial: "Tarte au Citron Meringuée Suisse",
dessertPremium: "Saint Honoré Vanille et Caramel",
dessertMix: "Crème Brûlée Française Classique",
dessertChocoPlate: "Sélection de Ligne de Macarons Premium",
dessertBerryPlate: "Dôme Brillant de Framboise Rose Velours",
dessertCreamyCup: "Tarte au Chocolat Noir et Fleur d'Or",
dessertExoticPlatter: "Verre de Panna Cotta aux Fruits Rouges",
dessertFruitCake: "Gâteau aux fruits frais",
dessertWalnutNest: "Nid d'oiseau aux noix",
dessertPistachioRoll: "Rouleau de baklava aux pistaches",
dessertAshtaNest: "Nid à la crème et aux pistaches",
dessertBasbousaPistachio: "Basboussa aux pistaches",
dessertBasbousaAlmond: "Basboussa aux amandes",
dessertWeddingCake: "Gâteau de mariage royal",
dessertAssortedBaklava: "Assortiment de pâtisseries orientales",
dessertKunafa: "Chafia traditionnelle à la crème",

    drinkBitterCoffee: "Café Noir Authentique",
drinkChampagne: "Champagne de Prestige",
drinkCocktail: "Cocktail de Fruits Exotiques",
drinkEnergyDrinks: "Boissons Énergisantes",
drinkFizzyDrinks: "Boissons Gazeuses Pétillantes",
drinkFreshJuice: "Jus de Fruits Frais",
drinkHerbalTea: "Infusion de Plantes Aromatiques",
drinkHotDrinks: "Boissons Chaudes Artisanales",
drinkMilkShake: "Milk-shake Velouté",
drinkWhiskey: "Whisky de Réserve Classique",

appetizerBabaGhanoush: "Tarte de Caviar d'Aubergine (Baba Ghanoush) de Luxe aux Feuilles d'Or",
appetizerBeefCarpaccio: "Plateau de Carpaccio de Bœuf Premium",
appetizerCheeseSambousek: "Sambousek au Fromage Croustillant à l'Or Comestible",
appetizerGoatCheeseHoney: "Tartelettes au Fromage de Chèvre et Miel au Caviar Brillant",
appetizerGourmetSambousek: "Sélection de Sambousek Gourmet Orientale Premium",
appetizerHummusFatteh: "Coupes de Fatteh d'Houmous Croustillantes aux Pignons et Or",
appetizerHummusCaviar: "Houmous Royal Décoré de Caviar Noir et Doré",
appetizerKibbehNayyeh: "Kibbeh Nayyeh de Luxe aux Herbes Fraîches et Or",
appetizerMiniQuiche: "Mini Quiche Cuite au Four Gourmet aux Paillettes d'Or",
appetizerDolma: "Feuilles de Vigne Farcies Premium (Dolma) au Caviar Noir",
appetizers: "Entrées",


food: "Plats Principaux",
  foodFiletMignon: "Filet Mignon Premium",
  foodFoieGras: "Foie Gras Royal",
  foodJagerschnitzel: "Jägerschnitzel Traditionnel",
  foodLobsterThermidor: "Homard Thermidor Gastronomique",
  foodPekingDuck: "Canard laqué de Pékin",
  foodRisottoAiFunghi: "Risotto aux Champignons Sauvages",
  foodSaffronRisotto: "Risotto au Safran et Feuille d'Or",
  foodSquidInkCalamari: "Calmar Farci à l'Encre de Seiche",
  foodTagliatelleTartufo: "Tagliatelle al Tartufo Nero",
  foodTurbotChampagne: "Turbot Sauce Champagne",

appetizerCrunchyRoastedChickpeas: "Pois chiches grillés croquants",
appetizerMarinatedOlives: "Olives marinées",
appetizerAleppoPistachios: "Pistaches d'Alep",
appetizerRoastedCashews: "Noix de cajou grillées",
appetizerRoastedMixedNuts: "Mélange de fruits secs grillés",
appetizerRoastedPumpkinSeeds: "Graines de citrouille grillées",
appetizerSaltedPeanuts: "Cacahuètes salées",
appetizerSaltedRoastedAlmonds: "Amandes grillées et salées",
appetizerShanklishCheese: "Fromage Shanklish aux légumes",


hallRoyalGrand: "Grande Salle Royale",
    hallCrystalBallroom: "Salle de Bal Cristal",
    hallGoldenOasis: "Salle Oasis Dorée",
    hallMajesticPalace: "Salle du Palais Majestueux",
    hallSapphireLounge: "Salon Saphir",
    hallEmeraldGarden: "Salle Jardin d'Émeraude",
    hallDiamondPavilion: "Pavillon Diamant",
    hallSunsetTerrace: "Salle Terrasse du Coucher de Soleil",
    hallVintageClassic: "Salle Classique Vintage",


"profile": "Profil",
  "availableBalance": "Solde disponible",
  "topUp": "Recharger",
  "fullName": "Nom complet",
  "phoneNumber": "Numéro de téléphone",
  "saveChanges": "Sauvegarder",
  "editProfile": "Modifier le profil",
  "topUpCard": "Recharger la carte",
  "enterAmount": "Entrez le montant",
  "cancel": "Annuler",
  "sendRequest": "Envoyer la demande",
  "appOptions": "Options de l'application",
  "support": "Support technique",
  "aboutApp": "À propos de l'application",
  "termsServices": "Conditions d'utilisation",
  "settings": "Paramètres",
  "success": "Succès",
  "error": "Erreur",
  "profileUpdated": "Profil mis à jour avec succès",
  "invalidAmount": "Veuillez entrer un montant valide supérieur à zéro",
  "requestSent": "Demande envoyée",
  "topUpPendingAdmin": "Votre demande de recharge a été envoyée à l'administrateur pour approbation.",

  helpCenter: "Aide & Support",
    paymentHistory: "Historique des paiements",
    settings: "Paramètres",
    termsConditions: "Conditions générales",
    logout: "Se déconnecter",
    availableBalance: "Solde disponible",
    topUp: "Recharger",
    editProfile: "Modifier le profil",
    moreOptions: "Options de l'application",
    topUpTitle: "Recharger le compte",
    enterAmount: "Entrez le montant pour l'admin",
    profileUpdated: "Profil et photo mis à jour instantanément",
    topUpRequestSent: "Demande de recharge envoyée à l'admin, en attente d'approbation",
    invalidAmount: "Veuillez entrer un montant valide",
    name: "Nom",
    email: "E-mail",
    password: "Mot de passe",
    saveChanges: "Enregistrer",
    cancel: "Annuler",
    send: "Envoyer",
    alertTitle: "Notification",
    comingSoon: "Bientôt disponible",



       'onboardingTitle1': "Planification d'événements",
    'onboardingDesc1': 'Planifiez et organisez vos événements facilement et professionnellement avec Eventak',
    'onboardingTitle2': 'Choisissez la Salle Parfaite',
    'onboardingDesc2': "Parcourez les meilleures salles et choisissez celle qui correspond à votre goût",
    'onboardingTitle3': 'Menu Complet',
    'onboardingDesc3': 'Choisissez parmi une large sélection de plats, boissons et desserts',
    'onboardingTitle4': "Voitures de Luxe pour vos Événements",
    'onboardingDesc4': 'Ajoutez une touche d\'élégance avec une collection de voitures premium',
    'skip': 'Passer',
    'next': 'Suivant',
    'getStarted': 'Commencer',
  },

  de: {
// أضف هذه الكلمات في قسم 'de'
login: "Einloggen",
fullName: "Vollständiger Name",
phonePlaceholder: "Telefonnummer",
otpPlaceholder: "Bestätigungscode eingeben (OTP)",
newPasswordPlaceholder: "Neues Passwort",
confirmPasswordPlaceholder: "Neues Passwort bestätigen",
savePassword: "Speichern und Passwort ändern",


    loginTitle: "Einloggen",
    loginSubtitle: "Sign in to manage your events",
    emailPlaceholder: "E-Mail-Adresse",
    passwordPlaceholder: "Passwort",
    btnCustomer: "Als Kunde anmelden",
    btnAgent: "Als Agent anmelden",
    alertTitle: "Hinweis",
    alertMessage: "Bitte E-Mail und Passwort eingeben",
    customerTitle: "Willkommen in Ihrem Event-Management",
    agentTitle: "Willkommen im Aufsichtsrat",
    logout: "Abmelden",
    changeLang: "Sprache",
    changeTheme: "Thema",
    home: "Startseite",
    notifications: "Benachrichtigungen",
    myEvents: "Meine Events",
    profile: "Profil",
    editProfile: "Profil bearbeiten",
    saveChanges: "Änderungen speichern",
    firstName: "Vorname",
    lastName: "Nachname",
    gender: "Geschlecht",
    birthday: "Geburtstag",
    confirmPassword: "Bestätigen",
    agreeTerms: "Ich stimme den Bedingungen zu",
    signup: "REGISTRIEREN",
    orSignInWith: "Oder melden Sie sich an mit",
    dontHaveAccount: "Kein Konto? ",
    createAccount: "Registrieren",
    alreadyHaveAccount: "Bereits ein Konto? ",
    loginHere: "Einloggen",
    selectGender: "Geschlecht auswählen",
    male: "Männlich",
    female: "Weiblich",
    noNotifications: "Momentan keine Benachrichtigungen",
    noEvents: "Keine Events erstellt",
    photoAlertTitle: "Profilbild",
    photoAlertMessage: "Wählen Sie eine Methode",
    camera: "Foto aufnehmen",
    gallery: "Aus Galerie wählen",


    cancel: "Abbrechen",
"forgotPassword": "Passwort vergessen",
  "forgotPasswordSubtitle": "Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Bestätigungscode",
  "sendResetCode": "Code senden",
  "backToLogin": "Zurück zum Login",
  "resetPassword": "Passwort zurücksetzen",
  "resetPasswordSubtitle": "Geben Sie den Bestätigungscode und Ihr neues Passwort ein",
  "otpCode": "Bestätigungscode (OTP)",
  "newPassword": "Neues Passwort",
  "confirmNewPassword": "Neues Passwort bestätigen",
  "resetPasswordBtn": "Passwort ändern",
  "enterEmailFirst": "Bitte geben Sie zuerst Ihre E-Mail-Adresse ein",
  "otpSentMessage": "Code zum Zurücksetzen des Passworts wurde an Ihre E-Mail gesendet",
  "fillAllFields": "Bitte füllen Sie alle Felder aus",
  "passwordChangedSuccess": "Passwort erfolgreich geändert. Sie können sich jetzt mit Ihrem neuen Passwort anmelden",
  "passwordMinLength": "Das Passwort muss mindestens 6 Zeichen lang sein",



    
   planNewEvent: "Planen Sie ein neues Event",
  approvedVenues: "Liste der genehmigten Veranstaltungsorte",
  myEventsList: "Meine Veranstaltungsliste",
  venueStatus: "Veranstaltungsort-Status",
  vendorStatus: "Lieferantenstatus",
  paymentInvoiceStatus: "Endrechnung & Zahlungsstatus",
  notificationsCenter: "Benachrichtigungszentrum",
  clearTokenLogout: "Abmelden & Token löschen",
  uploadAvatar: "Persönlichen Avatar hochladen",
    
    venue1: "Der Große Diamantsaal",
    venue2: "Samtrosen-Resort",
    serviceFood: "Königliches Abendbuffet",
    serviceFlowers: "VIP-Naturblumendesign",
    serviceCars: "Limousinen-Konvoi-Service",
    
    totalPrice: "Geschätzter Gesamtpreis",
    eventStatus: "Event-Status",
    statusPending: "Warten auf Bestätigung ⏳",
    statusConfirmed: "Bestätigt - Bereit für Anzahlung 💳",
    payDeposit: "Anzahlung jetzt zahlen",
    paymentSuccess: "Zahlung erfolgreich! Event gesichert ⚜️",

    celebratingTitle: "Was feiern wir heute?",
    createEventBtn: "✨ Event erstellen",
    selectEventType: "Ereignistyp auswählen",
    selectDate: "Datum & Uhrzeit auswählen",
    setBudget: "Gesamtbudget festlegen ($)",
    reviewSubmit: "Prüfen & Absenden",
    submitOrder: "👑 Anfrage absenden",
    budgetPlaceholder: "Z.B. 5000",
    
    wedding: "Hochzeiten",
    birthday: "Geburtstage",
    graduation: "Graduierungen",
    corporate: "Firmenkunden",
    funeral: "Beerdigungen",
    engagement: "Verlobungen",
    babyShower: "Babypartys 🍼",
    awards: "Preisverleihungen & Galas 🏆",
    
    food: "Catering & Essen",
    drinks: "Getränkebar",
    flowers: "Blumen & Bühne",
    cars: "VIP-Fuhrpark",
    sweets: "Kuchen & Süßigkeiten",
    fruits: "Früchtebuffet",

    appName: "⚜️ Evently Luxus",
    cartTitle: "Ausgewählte Services",
    remainingBudget: "Restbudget:",
    itemsCount: "Aktive Services",
    unit: "Einheit",
    exceededBudget: "⚠️ Warnung: Budget überschritten!",

    // Fruits DE
    fruitSculptures: "Tropische Fruchtskulpturen",
    fruitPlatterClassic: "Klassische gemischte Fruchtplatte",
    fruitBasketRoyal: "Königlicher Ananas-Fruchtkorb",
    fruitMelonBoat: "VIP Melonen-Fruchtboot",
    fruitTowerPremium: "Premium Etagere mit Früchten",
    fruitBowlMix: "Königliche Fruchtsalatschalen",
    pomegranatePlate: "Frischer Granatapfelteller",
    strawberryPlate: "Frischer Erdbeerteller",
    kiwiPlate: "Erfrischender Kiwischeiben-Teller",
    exoticFruitPlatter: "Seltene exotische Fruchtplatte",

    // Flowers DE
    blackStar: "Königliches Black Star Bouquet",
    boatOrchid: "Luxuriöses Samt-Kahn-Orchideen-Arrangement",
    camellia: "Klassische kaiserliche Kamelien-Vase",
    boldDaisy: "Warmes herbstliches Gänseblümchen-Bouquet",
    damaskRose: "Edle historische Damaszener-Rosen-Vase",
    hydrangea: "Königliches Hortensien & Premium-Dahlien",
    jasmine: "Frisches syrisches Jasmin & gelbe Rosen Design",
    narcissus: "Kaiserliches weiß-gelbes Narzissen-Setup",
    orichid: "Elegantes weiß-gelbes Orchideen-Arrangement",
    tulips: "Samtige rosa Harmonie-Tulpen-Vase",

    // VIP Cars DE
    carRollsClassic: "Königlicher klassischer Rolls-Royce",
    carAudiA8L: "Präsidenten-Luxus Audi A8L",
    carBentleySUV: "VIP Bentley Bentayga",
    carDefenderLuxury: "Königlicher verlängerter Land Rover Defender",
    carLimousineVIP: "Legendäre Stretch-Lincoln-Limousine",
    carMaybachSClass: "Spezielle Roségold Mercedes-Maybach",
    carMercedesCabrio: "Klassisches offenes Mercedes Cabrio",
    carMercedesGClass: "Luxus-Damaszener-Mercedes G-Klasse Konvoi",
    carPorschePanamera: "Premium sportlicher Porsche Panamera",
    carRollsPhantom: "Königlicher blauer Rolls-Royce Phantom",

    // Sweets DE
   // أضف هذه الأسطر داخل قسم "de" في ملف languages.js
dessertClassic: "Luxus Farbige Makronen-Pyramide",
dessertLuxury: "Weiße Erdbeer-Samtkuchen-Scheibe",
dessertRoyal: "Königlicher Himbeer-Glasurkuchen",
dessertSpecial: "Schweizer Baiser Zitronentarte",
dessertPremium: "Saint Honoré Vanille und Caramel",
dessertMix: "Klassische französische Crème Brûlée",
dessertChocoPlate: "Premium französische Makronen-Linienauswahl",
dessertBerryPlate: "Glänzende rosa Himbeer-Samtkuppel",
dessertCreamyCup: "Dunkle Schokoladentarte mit goldener Blume",
dessertExoticPlatter: "Premium gemischtes Beeren-Panna-Cotta-Glas",
dessertFruitCake: "Frischer Fruchtkuchen",
dessertWalnutNest: "Walnuss-Vogelnest",
dessertPistachioRoll: "Pistazien-Baklava-Rolle",
dessertAshtaNest: "Pistazien-Creme-Nest",
dessertBasbousaPistachio: "Pistazien-Basbousa",
dessertBasbousaAlmond: "Mandel-Basbousa",
dessertWeddingCake: "Königliche Hochzeitstorte",
dessertAssortedBaklava: "Premium sortierte orientalische Süßigkeiten",
dessertKunafa: "Traditionelle Kunafa mit Sahne",


    drinkBitterCoffee: "Authentischer Bitterer Kaffee",
drinkChampagne: "Premium-Luxus-Champagner",
drinkCocktail: "Exotischer Fruchtcocktail",
drinkEnergyDrinks: "Erfrischende Energiedrinks",
drinkFizzyDrinks: "Prickelnde Erfrischungsgetränke",
drinkFreshJuice: "Frisch Geklebte Säfte",
drinkHerbalTea: "Beruhigender Kräutertee",
drinkHotDrinks: "Warme handgemachte Heißgetränke",
drinkMilkShake: "Samtiger cremiger Milchshake",
drinkWhiskey: "Klassischer Reserve-Whisky",

appetizerBabaGhanoush: "Luxus Baba Ghanoush Tarte mit Blattgold",
appetizerBeefCarpaccio: "Premium Rinder-Carpaccio-Platte",
appetizerCheeseSambousek: "Knusprige Käse-Sambousek mit essbarem Gold",
appetizerGoatCheeseHoney: "Ziegenkäse-Honig-Törtchen mit glänzendem Kaviar",
appetizerGourmetSambousek: "Premium Sortierte Gourmet-Sambousek-Auswahl",
appetizerHummusFatteh: "Knusprige Hummus-Fatteh-Becher mit Pinienkernen & Gold",
appetizerHummusCaviar: "Königlicher Hummus-Teller mit schwarzem und goldenem Kaviar",
appetizerKibbehNayyeh: "Luxus Kibbeh Nayyeh Becher mit frischen Kräutern & Gold",
appetizerMiniQuiche: "Gourmet Mini-Backquiche mit Goldflocken",
appetizerDolma: "Premium Gefüllte Weinblätter (Dolma) mit schwarzem Kaviar",
appetizers: "Vorspeisen",


food: "Hauptgerichte",
  foodFiletMignon: "Premium Filet Mignon",
  foodFoieGras: "Königliche Foie Gras",
  foodJagerschnitzel: "Klassisches Jägerschnitzel",
  foodLobsterThermidor: "Exklusiver Hummer Thermidor",
  foodPekingDuck: "Traditionelle Pekingente",
  foodRisottoAiFunghi: "Wildpilz-Risotto ai Funghi",
  foodSaffronRisotto: "Safran-Risotto mit Blattgold",
  foodSquidInkCalamari: "Mit Tintenfischinte gefüllte Calamari",
  foodTagliatelleTartufo: "Tagliatelle al Tartufo Nero",
  foodTurbotChampagne: "Steinbutt mit Champagnersauce",


  appetizerCrunchyRoastedChickpeas: "Knusprig geröstete Kichererbsen",
appetizerMarinatedOlives: "Marinierte Oliven",
appetizerAleppoPistazien: "Aleppo-Pistazien",
appetizerRoastedCashews: "Geröstete Cashewnüsse",
appetizerRoastedMixedNuts: "Geröstete gemischte Nüsse",
appetizerRoastedPumpkinSeeds: "Geröstete Kürbiskerne",
appetizerSaltedPeanuts: "Gesalzene Erdnüsse",
appetizerSaltedRoastedAlmonds: "Geröstete und gesalzene Mandeln",
appetizerShanklishCheese: "Shanklish-Käse mit Gemüse",



hallRoyalGrand: "Königliche Große Halle",
    hallCrystalBallroom: "Kristall-Ballsaal",
    hallGoldenOasis: "Goldene Oase Halle",
    hallMajesticPalace: "Majestätische Palasthalle",
    hallSapphireLounge: "Saphir-Lounge",
    hallEmeraldGarden: "Smaragdgarten-Halle",
    hallDiamondPavilion: "Diamant-Pavillon",
    hallSunsetTerrace: "Sonnenterrasse-Halle",
    hallVintageClassic: "Klassische Vintage-Halle",



"profile": "Profil",
  "availableBalance": "Verfügbares Guthaben",
  "topUp": "Aufladen",
  "fullName": "Vollständiger Name",
  "phoneNumber": "Telefonnummer",
  "saveChanges": "Änderungen speichern",
  "editProfile": "Profil bearbeiten",
  "topUpCard": "Zahlungskarte aufladen",
  "enterAmount": "Betrag eingeben",
  "cancel": "Abbrechen",
  "sendRequest": "Anfrage senden",
  "appOptions": "App-Optionen",
  "support": "Technischer Support",
  "aboutApp": "Über die App",
  "termsServices": "Nutzungsbedingungen",
  "settings": "Einstellungen",
  "success": "Erfolgreich",
  "error": "Fehler",
  "profileUpdated": "Profil erfolgreich aktualisiert",
  "invalidAmount": "Bitte geben Sie einen gültigen Betrag größer als Null ein",
  "requestSent": "Anfrage gesendet",
  "topUpPendingAdmin": "Ihre Aufladeanfrage wurde zur Genehmigung an den Admin gesendet.",


helpCenter: "Hilfe & Support",
    paymentHistory: "Zahlungsverlauf",
    settings: "Einstellungen",
    termsConditions: "Allgemeine Bedingungen",
    logout: "Abmelden",
    availableBalance: "Verfügbares Guthaben",
    topUp: "Aufladen",
    editProfile: "Profil bearbeiten",
    moreOptions: "Anwendungsoptionen",
    topUpTitle: "Guthaben aufladen",
    enterAmount: "Betrag für den Admin eingeben",
    profileUpdated: "Profil und Foto sofort aktualisiert",
    topUpRequestSent: "Aufladeanfrage an den Admin gesendet, wartet auf Genehmigung",
    invalidAmount: "Bitte geben Sie einen gültigen Betrag ein",
   
    name: "Name",
    email: "E-Mail",
    password: "Passwort",
    saveChanges: "Speichern",
    cancel: "Abbrechen",
    send: "Senden",
    alertTitle: "Hinweis",
    comingSoon: "Demnächst verfügbar",



     'onboardingTitle1': 'Event- & Veranstaltungsplanung',
    'onboardingDesc1': 'Planen und organisieren Sie Ihre Events einfach und professionell mit Eventak',
    'onboardingTitle2': 'Wählen Sie den Perfekten Veranstaltungsort',
    'onboardingDesc2': 'Durchstöbern Sie die besten Veranstaltungssäle und wählen Sie nach Ihrem Geschmack',
    'onboardingTitle3': 'Komplettes Speisekarte',
    'onboardingDesc3': 'Wählen Sie aus einer großen Auswahl an Speisen, Getränken und Desserts',
    'onboardingTitle4': 'Luxusautos für Ihre Veranstaltungen',
    'onboardingDesc4': 'Fügen Sie mit einer Sammlung von Premium-Autos einen Hauch von Eleganz hinzu',
    'skip': 'Überspringen',
    'next': 'Weiter',
    'getStarted': 'Loslegen',



  }

};